version: "3.8"

services:
  app:
    container_name: nodeapp_container
    build:
      context: ./app/
      dockerfile: app.dockerfile
    environment:
      - DB_HOST=db:27017
    ports:
      - "80:3000"
    links:
      - db
    networks: 
      - nodeapp-network
  db:
    container_name: mongodb_for_nodeapp
    build:
      context: ./db/
      dockerfile: db.dockerfile
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks: 
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
