version: "3.8"

services:
  app:
    container_name: nodeapp_container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=127.0.0.1:27017
    ports:
      - "80:3000"
    links:
      - db
  db:
    image: mongo
    container_name: mongodb_for_nodeapp
    ports:
      - "27017:27017"
    restart: unless-stopped
